import 'bootstrap/dist/css/bootstrap.min.css';

import AOS from "aos";
import "aos/dist/aos.css";


// icon
import '../../public/icons/flaticon_mycollection.css';

import Layout from '@/Components/layout/Layout';
import Head from 'next/head';

import '@/styles/globals.css';
import '@/styles/media.css';
import store from '@/redux/store';
import { getTotals } from '@/redux/stateSlices/CartSlice';
import { Provider } from 'react-redux';
import ScrollToTop from 'react-scroll-to-top';
import { useEffect } from 'react';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export default function App({ Component, pageProps }) {
  store.dispatch(getTotals());

  useEffect(() => {
    AOS.init();
    AOS.refresh();
  }, []);

  return (
    

    <>
      <Head>
        <title>FewHue</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <Provider store={store}>
        <Layout>
      
          <Component {...pageProps} />
          <ScrollToTop smooth />
          <ToastContainer />
        </Layout>
      </Provider>

    </>

  )

}
